# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rent', models.IntegerField(default=1000)),
                ('type', models.CharField(max_length=200)),
                ('house', models.TextField(default='')),
                ('address', models.CharField(max_length=200)),
                ('community', models.TextField(default='')),
                ('circum', models.TextField(default='')),
                ('translate', models.TextField(default='')),
                ('installations', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('houseIntroduce', models.TextField()),
                ('distance', models.IntegerField(default=500)),
                ('housetype', models.CharField(choices=[('一室一厅一卫', '一室一厅一卫'), ('四室两厅两卫', '四室两厅两卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室一厅两卫', '三室一厅两卫'), ('三室两厅两卫', '三室两厅两卫'), ('三室一厅一卫', '三室一厅一卫')], max_length=200)),
                ('pic_max', models.ImageField(upload_to='house_pic')),
                ('pic_1', models.ImageField(upload_to='house_pic')),
                ('pic_2', models.ImageField(upload_to='house_pic')),
                ('pic_3', models.ImageField(upload_to='house_pic')),
                ('pic_4', models.ImageField(upload_to='house_pic')),
                ('pic_5', models.ImageField(upload_to='house_pic')),
                ('pic_6', models.ImageField(upload_to='house_pic')),
                ('pic_7', models.ImageField(upload_to='house_pic')),
                ('pic_8', models.ImageField(upload_to='house_pic')),
                ('pic_9', models.ImageField(upload_to='house_pic')),
                ('area_to', models.ManyToManyField(related_name='area_to', to='workapp.Area')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=10, unique=True)),
                ('password', models.CharField(blank=True, max_length=8)),
                ('phone_number', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('女', '女'), ('男', '男'), ('保密', '保密')], default='保密', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(default='avator/wenhao/jpg', upload_to='avatar')),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='house_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_title', to='workapp.HouseInfo'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workapp.UserInfo'),
        ),
    ]
